version: '1.0'
services:
  frontend:
    image: divinaventi/llama-frontend:prodv2
    environment: 
      PORT: 80
      PROXY_API: 
    ports:
      - 80:80
  webserver:
    #change to llama-web-server for the original llama weights and openllama-web-server
    #for the open sourced llama weights
    image: divinaventi/panda-web-server
    ports:
      - 8000:8000
